# Setup
title:        nocorica
tagline:      Fragments of Geek Life
baseurl:      ""
paginate:     1
permalink:    /:year/:month/:title 

# About/contact
author:
  name:       syon
  url:        https://github.com/syon

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
kramdown:
  input: GFM

# Analytics and webmaster tools stuff goes here
google_analytics: UA-37634759-1
